### ISSUE TITLE
Logo Creation

### ISSUE THREAD

**Issue by divyasri77** [Girl-Code-It/Opportunity-Calendar-Frontend#155] opened 2021-03-26 12:06 UTC
**ISSUE** : We can add a logo to your project to make it look more attractive</br>
**SOLUTION**: I will create a logo by using CANVA or by using ILLUSTRATOR
(GSSOC Participant)

**Comment by Hardik-07** [comment] 2021-03-27 09:54
I would like to help in creating LOGO , can you plss assign me this issue

**Comment by divyasri77** [comment] 2021-03-27 13:10
Can I work on it ? pls assign me

**Comment by abdus** [comment] 2021-03-27 15:10
Duplicate of #84. Closing...

**Closed as completed by abdus** 2021-03-27 15:10 UTC
