### ISSUE TITLE
add google authentication to react app

### ISSUE THREAD

**Issue by Muskan-creator** [Girl-Code-It/Opportunity-Calendar-Frontend#163] opened 2021-03-29 11:19 UTC
# Expected Behavior:

Please describe the behavior you are expecting.
![image](https://user-images.githubusercontent.com/59757988/112829190-6188da00-90ae-11eb-85c4-a59157ae1093.png)

# Current Behavior:

What is the current behavior?
there is no google authentication added so user has to fill his all details manually

# Solution:

Please describe what will you do to solve this issue or your approach to solve this issue.
We need to create an application in the Google developer console. It provides clientId is used to identify your application for authentication details.
![image](https://user-images.githubusercontent.com/59757988/112829399-b3c9fb00-90ae-11eb-8516-86fe52635160.png)

**Comment by abdus** [comment] 2021-03-29 16:44
I think this issue is a duplicate of #158. Please reopen if it is not.

**Closed as completed by abdus** 2021-03-29 16:44 UTC
