### ISSUE TITLE
Git Bot 

### ISSUE THREAD

**Issue by aishux** [Girl-Code-It/Opportunity-Calendar-Frontend#181] opened 2021-04-02 17:53 UTC
### **Feature request**:

A clear and concise description of the feature.

### **Is your feature request related to a problem? Please describe. (optional)**:

Add GitHub action to auto label issues with gssoc21 label when contributor asks to work under gssoc21. As it takes time for the maintainer to add labels, I can add a script that can auto-label issues with the GSSOC21 label whenever contributors ask to work under that label.

### **Describe the solution you'd like**:

I can add a script that can auto-label issues with the GSSOC21 label whenever contributors ask to work under that label.

### **Describe alternatives you've considered**:

none

### **Additional context:**

Please assign me this issue with a GSSOC tag and a level tag.

**Comment by vaishali614** [comment] 2021-04-02 19:03
@aishux This issue is a duplicate of #137. So I'm closing this issue. You can take up that issue if the assigned person is unable to complete it.

**Closed as completed by vaishali614** 2021-04-02 19:03 UTC
